### ISSUE TITLE
CLI is not working

### ISSUE THREAD

**Issue by terhardt** [codeinthehole/csvfilter#1]
Hey, it seems that the CLI is not working anymore. Running csvfilter always produces the following errors:

specifiying `-i`

```
    Traceback (most recent call last):
  File "/usr/local/bin/csvfilter", line 63, in <module>
    main(options, args)
  File "/usr/local/bin/csvfilter", line 11, in main
    processor = get_processor(options, args)
  File "/usr/local/bin/csvfilter", line 32, in get_processor
    mode=Processor.DROP if options.inverse else Processor.PLUCK)
  AttributeError: type object 'Processor' has no attribute 'DROP'
```

not specifiying `-i`

```
    Traceback (most recent call last):
  File "/usr/local/bin/csvfilter", line 63, in <module>
    main(options, args)
  File "/usr/local/bin/csvfilter", line 11, in main
    processor = get_processor(options, args)
  File "/usr/local/bin/csvfilter", line 32, in get_processor
    mode=Processor.DROP if options.inverse else Processor.PLUCK)
  AttributeError: type object 'Processor' has no attribute 'PLUCK'
```

**Comment by codeinthehole** [comment]
Now fixed.  It was due to me changing the processor API without checking the executable.  Now fixed with better tests.
