### ISSUE TITLE
Doesn't handle tab delimiter when specified from commandline

### ISSUE THREAD

**Issue by codeinthehole** [codeinthehole/csvfilter#7]
Instead you see

```
$ cat fixtures/sample.tsv | csvfilter -d "\t" -f2
Traceback (most recent call last):
  File "/usr/local/bin/csvfilter", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/david/Workspace/csvfilter/bin/csvfilter", line 59, in <module>
    main(options, args)
  File "/Users/david/Workspace/csvfilter/bin/csvfilter", line 13, in main
    pump(processor, infile, writer)
  File "/Users/david/Workspace/csvfilter/bin/csvfilter", line 36, in pump
    for output in processor.process(infile):
  File "/Users/david/Workspace/csvfilter/csvfilter/__init__.py", line 22, in process
    quotechar=self.quotechar)
TypeError: "delimiter" must be an 1-character string
```

**Comment by codeinthehole** [comment]
Fixed in 0.3.1
